export const PATH_ROUTE = {
  NOT_FOUND: "/404",
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/dang-ky-tai-khoan",
  FORGOT_PASSWORD: "/quen-mat-khau",
  PROFILE: "/thong-tin-ca-nhan",
  DASHBOARD: "/dashboard",
  DOCTORS: "/bac-si",
  FACILITYDETAIL: "/co-so",
  LISTFACILITY: "/danh-sach-co-so",
  LISTDOCTOR: "/danh-sach-bac-si",
  SPECIALISTEXAMINATION: "/kham-chuyen-khoa",
  GENERALEXAMINATION: "/kham-tong-quat",
} as const;
